basePath: /api/v1
definitions:
  api.Response:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
info:
  contact:
    email: khush.patibandha@gmail.com
    name: Khush Patibandha
  description: These are the APIs for VideoVerse take home assignment.
  title: VideoVerse API
  version: "1.0"
paths:
  /link:
    get:
      description: Generates a time-limited access link for a video using its ID
      parameters:
      - description: Video ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Response'
      security:
      - ApiKeyAuth: []
      summary: Generate a temporary link for a video
      tags:
      - video
  /merge:
    post:
      description: Merges two videos based on their IDs and returns a new merged video
        ID
      parameters:
      - description: First video ID
        in: query
        name: v1
        required: true
        type: integer
      - description: Second video ID
        in: query
        name: v2
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Response'
      security:
      - ApiKeyAuth: []
      summary: Merge two videos
      tags:
      - video
  /trim:
    put:
      description: Trims a video to the specified start and end time
      parameters:
      - description: Video ID
        in: query
        name: id
        required: true
        type: integer
      - description: Start time in seconds
        in: query
        name: s
        required: true
        type: integer
      - description: End time in seconds
        in: query
        name: e
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Response'
      security:
      - ApiKeyAuth: []
      summary: Trim a video
      tags:
      - video
  /uploads/{link}:
    get:
      description: Given a valid temporary link, redirects to the video file
      parameters:
      - description: Temporary video link
        in: path
        name: link
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: Video file served (Open in new tab or download)
          schema:
            type: file
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Response'
      summary: Redirect to the uploaded video
      tags:
      - video
  /video:
    post:
      consumes:
      - multipart/form-data
      description: Uploads a video file and returns a video ID for further operations
      parameters:
      - description: The video file to upload
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Response'
      security:
      - ApiKeyAuth: []
      summary: Upload a video
      tags:
      - video
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
